### ISSUE TITLE
The submit button with horizontal layout 

### ISSUE THREAD

**Issue by Lindorie** [felixarntz/bootstrap-for-contact-form-7#1]
Hi,

Thank you for this plugin, it is really useful!
I have changed the form layout to horizontal, but the submit button stays sticked on the left: 

![form_contact_issue](https://cloud.githubusercontent.com/assets/9593754/6318853/46f17358-baa6-11e4-9278-0a3120561a93.jpg)

Is there a way to fix this behaviour with the plugin?
For example, the submit button could be sticked on the right (bootstrap pull-right) or aligned like the label fields, below them.

Here's the code I use in Contact Form 7: 

```
[text* your-name]Votre nom[/text*]
[email* your-email]Votre email[/email*]
[text your-subject]Sujet[/text]
[textarea* your-message]Votre message[/textarea*]
[submit "Envoyer"]
```

I know I can use HTML and Bootstrap CSS classes around the submit shortcode, but I think it could be interesting if the plugin did this itself?

Thank you for reading me :)

**Comment by felixarntz** [comment]
Hi,

thanks for your request!

Indeed you're reporting an issue that I have been working around myself for quite a while.

What I'm curious about would be: I know that the submit button sticking to the left side of the overall form looks bad, but I'm not sure whether to align it to the left or right side of the input fields, concerning the appearance/UI. What do you prefer? I'd be interested in your thoughts.

Definitely something I will include in the next release. :)

**Comment by Lindorie** [comment]
Hmm, according to what I just read, the submit button would be better aligned in the left side of the input fields like this : 

![form_contact_issue3](https://cloud.githubusercontent.com/assets/9593754/6319798/d20bc1cc-baca-11e4-9d26-e46e9a2d8c1a.jpg)

The right side seems reserved to forms with several steps (with a "Next" button).
However I don't think it looks strange or non-ergonomic, even for a contact form : 

![form_contact_issue2](https://cloud.githubusercontent.com/assets/9593754/6319744/8f3a113e-bac8-11e4-9bef-bc3df3e2965a.jpg)

So maybe you can let the user choose himself the alignment he wants with another parameter ?

**Comment by felixarntz** [comment]
I have just [published a new version](https://downloads.wordpress.org/plugin/bootstrap-for-contact-form-7.1.1.0.zip) that does exactly that: The submit button is placed at the right position automatically (left by default), and you can specify the alignment with a new 'align' parameter which can have one of the values 'left', 'center' or 'right'.

Example: `[submit align:right "Send"]`

**Comment by Lindorie** [comment]
Thank you so much :) It works perfectly.
