### ISSUE TITLE
free_text attribute on checkbox and radio types

### ISSUE THREAD

**Issue by omnichronous** [felixarntz/bootstrap-for-contact-form-7#3]
Checkbox and radio button shortcodes have the optional **free_text** attribute, as documented [here](http://contactform7.com/checkboxes-radio-buttons-and-menus/), which adds a text input next to the last item of the set.

It would be really cool if you added support for that feature. I looked around the code to see if I could add it myself, but it's beyond me :)

If it helps, here's an example of how Contact Form 7 structures the output of the last item of the set by default:

``` html
<span class="wpcf7-list-item last has-free-text">
<label><input type="radio" name="NAME" value="VALUE">&nbsp;<span class="wpcf7-list-item-label">LABEL</span></label> <input type="text" name="_wpcf7_radio_free_text_NAME" class="wpcf7-free-text">
</span>
```

**Comment by felixarntz** [comment]
Hey, thanks for opening this issue! It's on my To Do list for the next release!

https://wordpress.org/support/topic/cf7-free_text-option-is-broken (same issue)

**Comment by omnichronous** [comment]
Thanks for all your hard work. The plugin is awesome, I was very frustrated to be unable to use it as my client really wanted that box. At the moment it's a choice between Bootstrapping the forms yourself, or doing the jQuery data binding thing manually - I opted for option one, but I'll make sure and update when you release the next version :)
