### ISSUE TITLE
Checkbox default value / preselect

### ISSUE THREAD

**Issue by JagBlack** [felixarntz/bootstrap-for-contact-form-7#34]
Hello, really a nice plugin to get contact form 7 working for bootstrap.
But there is onething I didn't get to work. I wanted to create an preselected checkbox as descriped in the original plugin:

> [checkbox nl default:1]my choice[/checkbox]

I'm not sure if the functionality is not supported or I'm just to stupid.

Thanks for the help in advance, JagBlack.

**Comment by felixarntz** [comment]
Hello JagBlack,

the problem is that you didn't specify values for the checkbox. Even if you only provide a single checkbox, it needs to have an option in order to use the default setting. For example:

`[checkbox nl default:1 "whatever value"]my choice[/checkbox]`
