### ISSUE TITLE
Radio and Checkbox Alignment

### ISSUE THREAD

**Issue by paulorenatojf** [felixarntz/bootstrap-for-contact-form-7#35]
Hi Felix,

I'm having issues with the alignment of the radio and checkboxes on my forms.
It occurs on Windows in most browsers and on Android, when your plugin is activated.

I have tried the default and group_layout option but both of them make the buttons display out of place. I'm not using the label_first option, but it does look like it...

Please take a look at my screen captures and see if you can help me pinpoint the problem.

Thanks a lot!

Paulo.

My form:
http://181.224.157.241/~spinife0/request-quote/

![bs_realdroid_mobile_google nexus 6-5 0-1440x2560-default](https://cloud.githubusercontent.com/assets/19216211/17633599/7dab25e2-60a4-11e6-8b32-b60e0ff404f2.jpg)
![bs_realdroid_mobile_samsung galaxy note 4-4 4-1440x2560-group-layout](https://cloud.githubusercontent.com/assets/19216211/17633600/7dad6a0a-60a4-11e6-8f5c-fdc3a404f9f3.jpg)

**Comment by felixarntz** [comment]
I'm not sure how this is happening, it is likely related to some CSS styles in your theme or another plugin.

The HTML code that Bootstrap for Contact Form 7 produces follows the regular Bootstrap conventions. I can't replicate the issue you're having, so I'd need some more details.

**Comment by gidomanders** [comment]
Since we did not receive any details for almost a year and we can not replicate the problem, I am closing this issue.
