### ISSUE TITLE
{input_before}@{/input_before} is not working with required fields

### ISSUE THREAD

**Issue by hilgigars** [felixarntz/bootstrap-for-contact-form-7#38]
For example:

`[text name class:form-control]{input_before}<i class="fa fa-user"></i>{/input_before}Name[/text]`
Is OK.

And this code will not work:
`[text* name class:form-control]{input_before}<i class="fa fa-user"></i>{/input_before}Имя[/text]`

**Comment by felixarntz** [comment]
Note that you have to add the asterisk in the closing tag as well. Then it should work.
