### ISSUE TITLE
Recent deprecated notices

### ISSUE THREAD

**Issue by mcgee993** [felixarntz/bootstrap-for-contact-form-7#39]
Just recently seen a lot of notices saying the following: 
Notice: wpcf7_add_shortcode is deprecated since Contact Form 7 version 4.6! Use wpcf7_add_form_tag instead. in ..../plugins/contact-form-7/includes/functions.php on line 351

This also causes it break styling as well but it is a quick fix, replace all "wpcf7_add_shortcode" with "wpcf7_add_form_tag". After you have done that you'll get a similar notice saying "WPCF7_Shortcode" is deprecated just replace it with "WPCF7_FormTag" and everything will work again.

**Comment by felixarntz** [comment]
Thanks for the report. There is a pull-request which I'm going to review soon in #40
