### ISSUE TITLE
Multi-column form with mandatory fields

### ISSUE THREAD

**Issue by javornikolov** [felixarntz/bootstrap-for-contact-form-7#45]
I'm trying to adapt an example given at https://wordpress.org/plugins/bootstrap-for-contact-form-7/other_notes/ about multi-column forms. The only change I have is that I'm trying to declare the fields as **mandatory** by adding `*` to the short-codes:
``` html
<div class="form-group row">
    <div class="col-md-6"><label for="user-first-name">First Name</label>[text* user_first_name id:user-first-name layout:none][/text*]</div>
    <div class="col-md-6"><label for="user-last-name">Last Name</label>[text* user_last_name id:user-last-name layout:none][/text*]</div>
</div>
```

The issue I have is that the fields are displayed as non-mandatory ones. And when not filled in - the error messages are not displayed, nor fields are marked as failed.

**Comment by gidomanders** [comment]
The additional settings, such as layout, should be defined in the Additional Settings tab of the form, not on the fields. Also when you want a label to show up correctly, you have to put the label in between the shortcodes. So your form should look like this:

```
<div class="form-group row">
    <div class="col-md-6">[text* user_first_name id:user-first-name]First Name[/text*]</div>
    <div class="col-md-6">[text* user_last_name id:user-last-name]Last Name[/text*]</div>
</div>
```
