### ISSUE TITLE
Not working with Really Simple captcha in 4.8

### ISSUE THREAD

**Issue by pyroweb** [felixarntz/bootstrap-for-contact-form-7#48]
Hello

Since upgrading to 4.8 this plugin does not work with really simple captcha (https://en-gb.wordpress.org/plugins/really-simple-captcha/)

If there is a RSC on a form with this plugin enabled this error message is displayed

Notice: Indirect modification of overloaded element of WPCF7_FormTag has no effect in /home/website/public_html/wp-content/plugins/bootstrap-for-contact-form-7/modules/really-simple-captcha.php on line 48

Fatal error: Call to undefined function wpcf7_captcha_shortcode_handler() in /home/website/public_html/wp-content/plugins/bootstrap-for-contact-form-7/modules/really-simple-captcha.php on line 51

**Comment by felixarntz** [comment]
This should be fixed with e128ee41244db4b296ae8044d4585c14a72cad34 and 647f29c10255ef222f3b846868b1356a4364d49e.
