### ISSUE TITLE
Can I set the number that is counted at the maximum length setting separately?

### ISSUE THREAD

**Issue by jinchungho** [felixarntz/bootstrap-for-contact-form-7#53]
Can I set the number that is counted at the maximum length setting separately?

**Comment by gidomanders** [comment]
The minlength and maxlength features are base Contact Form 7 features, so I think you should take a look at their own [website](https://contactform7.com/max-min-length-options-and-character-count/) or open an issue on their [support forum](https://wordpress.org/support/plugin/contact-form-7/).

**Comment by jinchungho** [comment]
Thank you for your answer.
