### ISSUE TITLE
CF7 toggleSubmit function not working for Acceptance Checkbox 

### ISSUE THREAD

**Issue by themagnifico** [felixarntz/bootstrap-for-contact-form-7#54]
Due to different DOM elements, the js toggleSubmit function does not find the input:checkbox.
So does not work correctly.

Using Contact Form 7 v 5.0 and Bootstrap for Contact Form 7 v 1.4.5 

Original CF7 code:
```html
<span class="wpcf7-form-control wpcf7-acceptance">
    <span class="wpcf7-list-item">
        <label>
            <input name="acceptance-995" value="1" aria-invalid="false" checked="checked" type="checkbox">
                <span class="wpcf7-list-item-label">Privacy text</span>
            </label>
        </span>
</span>
```

BS for CF7 code:
```html
<label>
    <input class="wpcf7-form-control wpcf7-acceptance" name="acceptance-995" value="1" checked="" aria-invalid="false" type="checkbox">Privacy text</label>
```

The CF7 js script search for:
```javascript		
$( '.wpcf7-acceptance', $form ).each( function() {
    var $span = $( this );
    var $input = $( 'input:checkbox', $span );
```

**Comment by themagnifico** [comment]
Thanks for the update, but still not working on my side.

The new code adds a wrapper class to the two parent divs and this is the result:

```html
<div class="form-group acceptance-995 wpcf7-acceptance">
    <div class="checkbox acceptance-995 wpcf7-acceptance">
        <label>
            <input class="wpcf7-form-control wpcf7-acceptance" name="acceptance-995" type="checkbox" value="1" checked="" aria-invalid="false">Privacy Text
        </label>
    </div>
</div>
```

Since also the input element has the class ```wpcf7-acceptance```, the js toggleSubmit function still fails and disables the submit button.

IMHO, I think that the easier way to solve the problem is to change the value of the following args, obtaining:

```php
'class'		=> '',  // no class in input element
'wrapper_class'	=> $tag_obj->get_class_option( $class ),
```

This is the result:
```html
<div class="form-group wpcf7-form-control wpcf7-acceptance">
   <div class="checkbox wpcf7-form-control wpcf7-acceptance">
      <label>
         <input name="acceptance-995" type="checkbox" value="1" checked="" aria-invalid="false">Privacy text
      </label>
   </div>
</div>
```

**Comment by gidomanders** [comment]
This is indeed still an issue. My test case did not exactly match your project. I have multiple test cases for the acceptance box now, to prevent this from happening again.

**Comment by Innivo** [comment]
Do you have 'Password Protected' plugin installed? De-activating that solved it for me.
