### ISSUE TITLE
bfcf7 make diseappear feedbacks of the CF7

### ISSUE THREAD

**Issue by Kahenos** [felixarntz/bootstrap-for-contact-form-7#59]
Hi !

By activating the plugin Bootstrap for CF7, all my automatics feedbacks (Valid or invalid submission) are not showing up. It's only showing an infinite loading
However, the automatic mail sending is functionnal on both sides (sender and destinator).

**Here what I see with btcf7 running**
![image](https://user-images.githubusercontent.com/6770277/43896095-e7623e6a-9bd7-11e8-8085-4b3f006a4aa7.png)

**Here the possibles feedback I would see (without btcf7 plugin activate)**
![image](https://user-images.githubusercontent.com/6770277/43896019-a2540b5a-9bd7-11e8-983e-44510024143d.png)

**I went through the console of my browser and see the below errors**
![image](https://user-images.githubusercontent.com/6770277/43896066-cd32e4f4-9bd7-11e8-88f9-c44829169eed.png)

**Is it something wrong throug my code below ?**
`[row]
[column width="1_2"][text* user-name]Nom et Prénom[/text*][/column]
[column width="1_2"][tel* user-telephone]Numéro de Téléphone[/tel*][/column]
[/row]

[row]
[column width="1_2"][email* user-email]Votre Email[/email*][/column]
[column width="1_2"]<label>Nationalité:</label>[select Paysdorigine include_blank "Afghanistan" "Afrique du Sud" "Akrotiri" "Albanie" "Algérie" "Allemagne" "Andorre" "Angola" "Anguilla" "Antarctique" "Antigua-et-Barbuda" "Antilles néerlandaises" "Arabie saoudite" "Arctic Ocean" "Argentine" "Arménie" "Aruba" "Ashmore and Cartier Islands" "Atlantic Ocean" "Australie" "Autriche" "Azerbaïdjan" "Bahamas" "Bahreïn" "Bangladesh" "Barbade" "Belau" "Belgique" "Belize" "Bénin" "Bermudes" "Bhoutan" "Biélorussie" "Birmanie" "Bolivie" "Bosnie-Herzégovine" "Botswana" "Brésil" "Brunei" "Bulgarie" "Burkina Faso" "Burundi" "Cambodge" "Cameroun" "Canada" "Cap-Vert" "Chili" "Chine" "Chypre" "Clipperton Island" "Colombie" "Comores" "Congo" "Coral Sea Islands" "Corée du Nord" "Corée du Sud" "Costa Rica" "Côte d'Ivoire" "Croatie" "Cuba" "Danemark" "Dhekelia" "Djibouti" "Dominique" "Égypte" "Émirats arabes unis" "Équateur" "Érythrée" "Espagne" "Estonie" "États-Unis" "Éthiopie" "ex-République yougoslave de Macédoine" "Finlande" "France" "Gabon" "Gambie" "Gaza Strip" "Géorgie" "Ghana" "Gibraltar" "Grèce" "Grenade" "Groenland" "Guam" "Guatemala" "Guernsey" "Guinée" "Guinée équatoriale" "Guinée-Bissao" "Guyana" "Haïti" "Honduras" "Hong Kong" "Hongrie" "Ile Bouvet" "Ile Christmas" "Ile Norfolk" "Iles Cayman" "Iles Cook" "Iles des Cocos (Keeling)" "Iles Falkland" "Iles Féroé" "Iles Fidji" "Iles Géorgie du Sud et Sandwich du Sud" "Iles Heard et McDonald" "Iles Marshall" "Iles Pitcairn" "Iles Salomon" "Iles Svalbard et Jan Mayen" "Iles Turks-et-Caicos" "Iles Vierges américaines" "Iles Vierges britanniques" "Inde" "Indian Ocean" "Indonésie" "Iran" "Iraq" "Irlande" "Islande" "Israël" "Italie" "Jamaïque" "Jan Mayen" "Japon" "Jersey" "Jordanie" "Kazakhstan" "Kenya" "Kirghizistan" "Kiribati" "Koweït" "Laos" "Lesotho" "Lettonie" "Liban" "Liberia" "Libye" "Liechtenstein" "Lituanie" "Luxembourg" "Macao" "Madagascar" "Malaisie" "Malawi" "Maldives" "Mali" "Malte" "Man, Isle of" "Mariannes du Nord" "Maroc" "Maurice" "Mauritanie" "Mayotte" "Mexique" "Micronésie" "Moldavie" "Monaco" "Monde" "Mongolie" "Monténégro" "Montserrat" "Mozambique" "Namibie" "Nauru" "Navassa Island" "Népal" "Nicaragua" "Niger" "Nigeria" "Nioué" "Norvège" "Nouvelle-Calédonie" "Nouvelle-Zélande" "Oman" "Ouganda" "Ouzbékistan" "Pacific Ocean" "Pakistan" "Panama" "Papouasie-Nouvelle-Guinée" "Paracel Islands" "Paraguay" "Pays-Bas" "Pérou" "Philippines" "Pologne" "Polynésie française" "Porto Rico" "Portugal" "Qatar" "République centrafricaine" "République démocratique du Congo" "République dominicaine" "République tchèque" "Roumanie" "Royaume-Uni" "Russie" "Rwanda" "Sahara occidental" "Saint-Christophe-et-Niévès" "Sainte-Hélène" "Sainte-Lucie" "Saint-Marin" "Saint-Pierre-et-Miquelon" "Saint-Siège" "Saint-Vincent-et-les-Grenadines" "Salvador" "Samoa" "Samoa américaines" "Sao Tomé-et-Principe" "Sénégal" "Serbie" "Seychelles" "Sierra Leone" "Singapour" "Slovaquie" "Slovénie" "Somalie" "Soudan" "Southern Ocean" "Spratly Islands" "Sri Lanka" "Suède" "Suisse" "Suriname" "Swaziland" "Syrie" "Tadjikistan" "Taïwan" "Tanzanie" "Tchad" "Terres australes françaises" "Territoire britannique de l'Océan Indien" "Thaïlande" "Timor Oriental" "Togo" "Tokélaou" "Tonga" "Trinité-et-Tobago" "Tunisie" "Turkménistan" "Turquie" "Tuvalu" "Ukraine" "Union européenne" "Uruguay" "Vanuatu" "Venezuela" "Viêt Nam" "Wake Island" "Wallis-et-Futuna" "West Bank" "Yémen" "Zambie" "Zimbabwe"][/column]
[/row]
[row]
[column width="1_2"]
Par quel biais vous contacter ?
[radio radio-contact id:radio-contact default:1 "Téléphone" "E-mail"]
[/column]
[column width="1_2"]
Je suis
[radio sex-contact id:sex-contact default:1 "Une femme" "Un homme"]
[/column]
[/row]
[row][column width="1_1"]
[textarea* message]Expliquez nous vos raisons et attentes pour votre consultation. [/textarea*]
[/column][/row]

[row][column width="1_1"]
[recaptcha]
[/column][/row]

<div class="text-center">[submit class:btn-long "Envoyer"]</div>`

**In advance, many thanks for your help guys**

**Comment by gidomanders** [comment]
It is not your form content that causes such errors in the console. It looks like the Contact Form 7 script is loaded after the BFCF7 script. `cannot set property 'notValidTip' of undefined` refers to `window.wpcf7.notValidTip`, where `window.wpcf7` is defined by the Contact Form 7 plugin script.

**Comment by Kahenos** [comment]
Thanks ! solved it
