### ISSUE TITLE
Displaying a group of radio buttons inline

### ISSUE THREAD

**Issue by wukerplank** [felixarntz/bootstrap-for-contact-form-7#6]
I'm trying to get two radio buttons to display inline. I tried it with the `group_layout` options from the docs like this:

```
[radio gender group_layout:inline default:1 "Male" "Female"]Gender*[/radio]
```

I expected them to appear like this:

![bildschirmfoto 2015-06-03 um 13 02 10](https://cloud.githubusercontent.com/assets/2319/7958554/cdc2f75a-09f0-11e5-9b51-74afac544571.png)

But the radio buttons remain vertical:

![bildschirmfoto 2015-06-03 um 13 00 40](https://cloud.githubusercontent.com/assets/2319/7958536/a918e4be-09f0-11e5-887e-17111866bd9f.png)

If I change the default value in `function cf7bs_get_default_form_properties` (bootstrap-for-contact-form-7.php), but I don't want to change the plugin's source code.

**Comment by felixarntz** [comment]
The 'group_layout' setting is a form setting, not a setting of an individual field. So you can only set it for a form as a whole.

To do so, you don't need to change the plugin's source code, you can use a filter for that.

For example, if the form you want to adjust has the ID 44, just add the following code somewhere:

``` php
function yourprefix_adjust_form_properties( $properties ) {
    $properties['group_layout'] = 'inline';
    return $properties;
}
add_filter( 'cf7bs_form_44_properties', 'yourprefix_adjust_form_properties' );
```

This will make all checkboxes/radio groups in that form appear inline.

Or if you want to change this behavior to apply to all forms on your site, replace the last line of the above snippet with the following:

``` php
add_filter( 'cf7bs_default_form_properties', 'yourprefix_adjust_form_properties' );
```

Hope I could help you here!

**Comment by wukerplank** [comment]
Wow, very helpful! Thanks a lot!
