### ISSUE TITLE
Required* Radio Fails to Render

### ISSUE THREAD

**Issue by bryanwillis** [felixarntz/bootstrap-for-contact-form-7#8]
[radio\* radio-415 "Yes" "No"]choose yes or no[/radio*]

When adding the required asterisks to a radio field, it doesn't render out the radios at all in the frontend. The field radios just show up like the shortcode shown above.

Here is a live demo of issue:

http://disputebills.com/broken-required-radio-boxes/
https://wordpress.org/plugins/bootstrap-for-contact-form-7/

**Comment by felixarntz** [comment]
This is actually not a bug. For radio buttons, adding the required asterisk is not supported as stated in the [docs of the original Contact Form 7 plugin](http://contactform7.com/checkboxes-radio-buttons-and-menus/).

**Comment by bryanwillis** [comment]
Thanks felix
